# Generated by Django 5.2.3 on 2025-07-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fame', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
